### ISSUE TITLE
Demonstrate API Gateway to Senzing API server

### ISSUE THREAD

**Issue by docktermj** [Senzing/community-roadmap#10]
**Is your feature request related to a problem? Please describe.**
The [Senzing API server](https://github.com/Senzing/senzing-api-server) provides a micro-service.
That is: it does not support authentication, authorization, load-balancing, etc.
By itself, it should not be exposed to the public.

**Describe the solution you'd like**
An [API Gateway pattern](https://microservices.io/patterns/apigateway.html) needs to be demonstrated on how to "front" the Senzing API server.

The examples may include:

1. [AWS API Gateway](https://aws.amazon.com/api-gateway/)
    1. The AWS API Gateway points to  a load-balancer that routes to scaleable senzing-api-server containers.
1. [Nginx proxy](https://www.nginx.com/learn/api-gateway/)
    1. [Deploying NGINX Plus as an API Gateway](https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-1/)

**Comment by docktermj** [comment]
API Gateway could also proxy  to [entity-search-web-app](https://github.com/Senzing/entity-search-web-app) containers

**Comment by jamietypovsky** [comment]
NOTE:  There are issues with timeouts on AWS API Gateway.  We should use TLS.

**Comment by jamietypovsky** [comment]
Taking a different approach - - > #48 
So we are closing this item.
