### ISSUE TITLE
Example ELK stack for monitoring Senzing

### ISSUE THREAD

**Issue by docktermj** [Senzing/community-roadmap#16]
Demonstrate Senzing monitoring with an ELK Stack (Elasticsearch, Logstash, and Kibana)

**Comment by docktermj** [comment]
Work being done in https://github.com/Senzing/docker-compose-demo/issues/205

**Comment by SamMacy** [comment]
Formation with example ELK stack exists in this docker-compose https://github.com/Senzing/docker-compose-demo/blob/main/resources/postgresql/docker-compose-rabbitmq-postgresql-with-ELK.yaml
