### ISSUE TITLE
python/docker to transfer data from one queue to another

### ISSUE THREAD

**Issue by docktermj** [Senzing/community-roadmap#40]
Sometimes we need to move files from the "dead-letter"/failure queue to the input queue  (For both original records and for redo records)

We need a generic method of "transferring" messages from one queue to another. Since we currently support RabbitMQ, Kafka, and SQS queue,  we need a program that knows how to read of any of the queue types and write to any of the queue types.

A Dockerfile can also be made to simplify deployment of the functionality

**Comment by jamietypovsky** [comment]
N/A
