### ISSUE TITLE
Determine an appropriate communication platform

### ISSUE THREAD

**Issue by docktermj** [Senzing/community-roadmap#41]
**Is your feature request related to a problem? Please describe.**
To build the Senzing Community, a place to congregate to discuss topics that may span multiple repositories (or no repositories).

Perhaps a "forum" platform is appropriate.

**Comment by roncewind** [comment]
Comparison can be found [here](https://github.com/Senzing/knowledge-base/blob/master/proposals/community-forum-comparison.md)

**Comment by roncewind** [comment]
Next step is to have a talk about the pros/cons of each solution.

**Comment by roncewind** [comment]
The decision is to try out Discourse.  For my notes click [here](https://github.com/Senzing/knowledge-base/blob/master/proposals/community-forum-comparison.md).
