### ISSUE TITLE
docker-compose formation showing replication to elastic search

### ISSUE THREAD

**Issue by docktermj** [Senzing/community-roadmap#43]
Implemented via:

1. https://github.com/Senzing/docker-compose-demo/issues/224

**Comment by docktermj** [comment]
@brianmacy Can you add more background?

**Comment by docktermj** [comment]
- **Potential repository:*  senzing-listener-example
- **Image name:** senzing/senzing-listener-example:latest
- **Demonstration:** Modify https://github.com/Senzing/docker-compose-demo/blob/main/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml

**Comment by SamMacy** [comment]
Similar functionality being created in elasticsearch issue [17](https://github.com/Senzing/elasticsearch/issues/17)
