### ISSUE TITLE
CloudFormation on AWS for deploying the REST API for a developer

### ISSUE THREAD

**Issue by brianmacy** [Senzing/community-roadmap#48]
Use SSL certificates for client authentication instead of Cognito.

ALB is desirable.

Swagger is also desirable but is more interesting as it should be behind User Authentication (e.g. Cognito) but should be communicating to the REST API with SSL certs.

**Comment by docktermj** [comment]
This work is being done in https://github.com/Senzing/aws-cloudformation-dev-rest
