### ISSUE TITLE
Add header / banner to GitHub assets, these are accelerators and examples, learn from, adjust, make your own

### ISSUE THREAD

**Issue by antaenc** [Senzing/community-roadmap#57]
We need it to be front and center that our assets are accelerators/demonstrators only. We cannot account for every container environment, specific customer customization and their own environmental requirements etc. 

It should be clear and at the top of assets customers use what we build, learn from them, tweak them and ultimately build their own with their own specific needs.

**Comment by jamietypovsky** [comment]
This is a dup of #55
