### ISSUE TITLE
Create "micro-batch" ingestion from external queue

### ISSUE THREAD

**Issue by docktermj** [Senzing/community-roadmap#6]
**Is your feature request related to a problem? Please describe.**
Some queues charge by the message.  When one record is sent per queue message, the cost can add up for many small records.

**Describe the solution you'd like**
Support the ability to pack (and then later unpack) multiple records into a single queue message.

### Supporting issues

1. https://github.com/Senzing/stream-producer/issues/39
2. https://github.com/Senzing/stream-loader/issues/84
3. https://github.com/Senzing/redoer/issues/47

**Comment by jeffadair** [comment]
stream-producer and stream-loader complete. stream-logger does not need to change. Just redoer remains.

**Comment by jeffadair** [comment]
For now, we are waiting until Senzing returns redo records as json, which is a commonly desired feature but there is no schedule for when that will be.

If there is a compelling reason to do it sooner, we will reasses.
